// ===== 100 FRASES =====
const quotes = [
  // Filosóficas / Lei da Atração
  { text: "O que você pensa, você atrai. O que você sente, você cria.", author: "" },
  { text: "Confie no tempo do universo. Tudo chega na hora certa.", author: "" },
  { text: "Suas vibrações criam sua realidade.", author: "" },
  { text: "Gratidão é o ímã mais poderoso para a abundância.", author: "" },
  { text: "O que é seu, te encontra.", author: "" },
  { text: "Você é o universo se experimentando.", author: "Alan Watts" },
  { text: "Onde foco vai, energia flui.", author: "" },
  { text: "Pequenos passos também são progresso.", author: "" },
  { text: "A jornada é tão importante quanto o destino.", author: "" },
  { text: "Você se torna aquilo em que acredita.", author: "Oprah Winfrey" },
  { text: "O universo conspira a favor de quem tem fé.", author: "" },
  { text: "Energia não mente. Confie no que você sente.", author: "" },
  { text: "Tudo que você precisa já está dentro de você.", author: "" },
  { text: "Manifeste como se já fosse seu.", author: "" },
  { text: "Seja a energia que você quer atrair.", author: "" },
  { text: "O presente é o único momento que existe.", author: "Eckhart Tolle" },
  { text: "Você não está atrasada. Está exatamente onde precisa estar.", author: "" },
  { text: "Confie no processo, mesmo quando não entender.", author: "" },
  { text: "Sua intuição sabe coisas que sua mente ainda não entendeu.", author: "" },
  { text: "O que floresce em você, floresce ao seu redor.", author: "" },
  { text: "A mente é tudo. O que você pensa, você se torna.", author: "Buda" },
  { text: "Seja paciente com seu crescimento.", author: "" },
  { text: "Você é mais do que seus pensamentos ruins.", author: "" },
  { text: "Permita-se recomeçar quantas vezes precisar.", author: "" },
  { text: "O universo recompensa a coragem.", author: "" },
  
  // Motivacionais modernas
  { text: "Hoje eu escolho a minha melhor versão.", author: "" },
  { text: "Você é mais forte do que qualquer obstáculo.", author: "" },
  { text: "Respira. Você dá conta.", author: "" },
  { text: "Tô aqui, tô tentando, tá ótimo.", author: "" },
  { text: "Bora arrasar hoje, gata.", author: "" },
  { text: "Você merece todas as coisas boas.", author: "" },
  { text: "Não tenha pressa de ser tudo de uma vez.", author: "" },
  { text: "Glow up é diário.", author: "" },
  { text: "Sua era está chegando. Se prepara.", author: "" },
  { text: "Romantize sua própria vida.", author: "" },
  { text: "Main character energy hoje.", author: "" },
  { text: "Você é a protagonista da sua história.", author: "" },
  { text: "Trust the timing of your life.", author: "" },
  { text: "Good things take time.", author: "" },
  { text: "She believed she could, so she did.", author: "R.S. Grey" },
  { text: "Be your own kind of beautiful.", author: "" },
  
  // Filmes e Séries icônicas
  { text: "Maybe some women aren't meant to be tamed.", author: "Sex and the City" },
  { text: "I'm looking for love. Real love. Ridiculous, inconvenient, consuming, can't-live-without-each-other love.", author: "Sex and the City" },
  { text: "The most exciting, challenging and significant relationship of all is the one you have with yourself.", author: "Sex and the City" },
  { text: "A million girls would kill for this job.", author: "O Diabo Veste Prada" },
  { text: "By all means, move at a glacial pace. You know how that thrills me.", author: "O Diabo Veste Prada" },
  { text: "Que a sorte esteja sempre ao seu favor.", author: "Jogos Vorazes" },
  { text: "Hope is the only thing stronger than fear.", author: "Jogos Vorazes" },
  { text: "Não são nossas habilidades que mostram quem somos, são nossas escolhas.", author: "Harry Potter" },
  { text: "A felicidade pode ser encontrada até nos momentos mais difíceis, basta lembrar de acender a luz.", author: "Dumbledore" },
  { text: "É preciso muita coragem para enfrentar nossos inimigos, mas ainda mais para enfrentar nossos amigos.", author: "Harry Potter" },
  { text: "Palavras são, na minha nada humilde opinião, nossa fonte mais inesgotável de magia.", author: "Dumbledore" },
  { text: "And so the lion fell in love with the lamb.", author: "Crepúsculo" },
  { text: "You don't know how long I've waited for you.", author: "Crepúsculo" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "Senhor dos Anéis" },
  { text: "Even the smallest person can change the course of the future.", author: "Senhor dos Anéis" },
  { text: "Why so serious?", author: "Coringa" },
  { text: "I am Iron Man.", author: "Vingadores" },
  { text: "I can do this all day.", author: "Capitão América" },
  { text: "With great power comes great responsibility.", author: "Homem-Aranha" },
  { text: "May the Force be with you.", author: "Star Wars" },
  { text: "Just keep swimming.", author: "Procurando Nemo" },
  { text: "Hakuna Matata.", author: "Rei Leão" },
  { text: "To infinity and beyond!", author: "Toy Story" },
  { text: "Life is like a box of chocolates. You never know what you're gonna get.", author: "Forrest Gump" },
  { text: "After all this time? Always.", author: "Harry Potter" },
  { text: "I'm also just a girl, standing in front of a boy, asking him to love her.", author: "Um Lugar Chamado Notting Hill" },
  { text: "Here's looking at you, kid.", author: "Casablanca" },
  { text: "I'll be there for you.", author: "Friends" },
  { text: "How you doin'?", author: "Friends" },
  { text: "We were on a break!", author: "Friends" },
  { text: "It's not a phase, mom!", author: "Cultura Pop" },
  { text: "That's hot.", author: "Paris Hilton" },
  { text: "I'm not like a regular mom, I'm a cool mom.", author: "Meninas Malvadas" },
  { text: "On Wednesdays we wear pink.", author: "Meninas Malvadas" },
  { text: "You go, Glen Coco!", author: "Meninas Malvadas" },
  { text: "I'm in a glass case of emotion!", author: "Âncora" },
  { text: "Yer a wizard, Harry.", author: "Harry Potter" },
  { text: "Winter is coming.", author: "Game of Thrones" },
  { text: "The night is dark and full of terrors.", author: "Game of Thrones" },
  { text: "I drink and I know things.", author: "Game of Thrones" },
  { text: "How lucky I am to have something that makes saying goodbye so hard.", author: "Ursinho Pooh" },
  { text: "You is kind. You is smart. You is important.", author: "Histórias Cruzadas" },
  { text: "I'm flying, Jack!", author: "Titanic" },
  { text: "Never let go.", author: "Titanic" },
  { text: "You had me at hello.", author: "Jerry Maguire" },
  { text: "Carpe diem. Seize the day.", author: "Sociedade dos Poetas Mortos" },
  { text: "Stay gold, Ponyboy.", author: "The Outsiders" },
  { text: "I see dead people.", author: "O Sexto Sentido" },
  { text: "Houston, we have a problem.", author: "Apollo 13" },
  { text: "You can't sit with us!", author: "Meninas Malvadas" },
  { text: "I'm the king of the world!", author: "Titanic" },
  { text: "É preciso ser louco para sonhar.", author: "" },
  { text: "A vida começa fora da zona de conforto.", author: "" },
  { text: "Não espere por oportunidades, crie elas.", author: "" },
  { text: "Done is better than perfect.", author: "" },
  { text: "Comparação é o ladrão da alegria.", author: "Theodore Roosevelt" },
  { text: "Você é a soma das suas escolhas.", author: "" },
  { text: "Coragem não é ausência de medo, é seguir mesmo com ele.", author: "" },
  { text: "O sucesso é a soma de pequenos esforços repetidos.", author: "Robert Collier" },
  { text: "Seja a mudança que você quer ver no mundo.", author: "Gandhi" },
  { text: "A única forma de fazer um trabalho excelente é amar o que você faz.", author: "Steve Jobs" }
];

// ===== ESTILOS MUSICAIS + ARTISTAS =====
// Nota: title = artista, artist = estilo (pra encaixar no layout do daily hub)
const musics = [
  { title: "Clairo", artist: "Indie Pop", genre: "Indie Pop" },
  { title: "Phoebe Bridgers", artist: "Indie Pop", genre: "Indie Pop" },
  { title: "Cuco", artist: "Bedroom Pop", genre: "Bedroom Pop" },
  { title: "Beabadoobee", artist: "Bedroom Pop", genre: "Bedroom Pop" },
  { title: "Nujabes", artist: "Lo-fi Hip Hop", genre: "Lo-fi Hip Hop" },
  { title: "Daniel Caesar", artist: "Soul", genre: "Soul" },
  { title: "H.E.R.", artist: "Soul", genre: "Soul" },
  { title: "Erykah Badu", artist: "Neo-soul", genre: "Neo-soul" },
  { title: "Jorja Smith", artist: "Neo-soul", genre: "Neo-soul" },
  { title: "SZA", artist: "R&B Alternativo", genre: "R&B Alternativo" },
  { title: "Frank Ocean", artist: "R&B Alternativo", genre: "R&B Alternativo" },
  { title: "Norah Jones", artist: "Jazz Vocal", genre: "Jazz Vocal" },
  { title: "Laufey", artist: "Jazz Contemporâneo", genre: "Jazz Contemporâneo" },
  { title: "João Gilberto", artist: "Bossa Nova", genre: "Bossa Nova" },
  { title: "Marisa Monte", artist: "MPB", genre: "MPB" },
  { title: "Tim Maia", artist: "MPB", genre: "MPB" },
  { title: "Jorge Ben Jor", artist: "Samba Soul", genre: "Samba Soul" },
  { title: "Ludmilla", artist: "Funk Carioca Melódico", genre: "Funk Carioca Melódico" },
  { title: "Anavitória", artist: "Pop Brasileiro", genre: "Pop Brasileiro" },
  { title: "Tiago Iorc", artist: "Pop Brasileiro", genre: "Pop Brasileiro" },
  { title: "Far From Alaska", artist: "Indie Brasileiro", genre: "Indie Brasileiro" },
  { title: "Bon Iver", artist: "Indie Folk", genre: "Indie Folk" },
  { title: "Hozier", artist: "Indie Folk", genre: "Indie Folk" },
  { title: "Lord Huron", artist: "Folk Pop", genre: "Folk Pop" },
  { title: "Arctic Monkeys", artist: "Alt Rock", genre: "Alt Rock" },
  { title: "The 1975", artist: "Alt Rock", genre: "Alt Rock" },
  { title: "Beach House", artist: "Dream Pop", genre: "Dream Pop" },
  { title: "Cigarettes After Sex", artist: "Dream Pop", genre: "Dream Pop" },
  { title: "The Weeknd", artist: "Synthpop", genre: "Synthpop" },
  { title: "Dua Lipa", artist: "Synthpop", genre: "Synthpop" },
  { title: "ODESZA", artist: "Eletrônico Chill", genre: "Eletrônico Chill" },
  { title: "Disclosure", artist: "House", genre: "House" },
  { title: "Fred again..", artist: "Deep House", genre: "Deep House" },
  { title: "IU", artist: "K-Pop Soft", genre: "K-Pop Soft" },
  { title: "NewJeans", artist: "K-Pop", genre: "K-Pop" },
  { title: "Crush", artist: "K-Indie", genre: "K-Indie" },
  { title: "DEAN", artist: "K-R&B", genre: "K-R&B" },
  { title: "Jay Park", artist: "K-Hip Hop", genre: "K-Hip Hop" },
  { title: "Yorushika", artist: "J-Pop", genre: "J-Pop" },
  { title: "Mariya Takeuchi", artist: "City Pop", genre: "City Pop" },
  { title: "Natiruts", artist: "Reggae Brasileiro", genre: "Reggae Brasileiro" },
  { title: "Rosalía", artist: "Latin Pop", genre: "Latin Pop" },
  { title: "Karol G", artist: "Reggaeton Pop", genre: "Reggaeton Pop" },
  { title: "Bad Bunny", artist: "Trap Latino", genre: "Trap Latino" },
  { title: "Djonga", artist: "Rap Nacional", genre: "Rap Nacional" },
  { title: "Tasha & Tracie", artist: "Rap Feminino BR", genre: "Rap Feminino BR" },
  { title: "Matuê", artist: "Trap BR", genre: "Trap BR" },
  { title: "A Tribe Called Quest", artist: "Hip Hop Old School", genre: "Hip Hop Old School" },
  { title: "Kendrick Lamar", artist: "Hip Hop Conscious", genre: "Hip Hop Conscious" },
  { title: "Lorde", artist: "Pop Indie", genre: "Pop Indie" }
];

// ===== DESAFIOS DE COMIDA =====
const foods = [
  { name: "🟡 Coma algo amarelo hoje", description: "Banana, milho, manga..." },
  { name: "🟢 Coma algo verde hoje", description: "Brócolis, kiwi, espinafre..." },
  { name: "🔴 Coma algo vermelho hoje", description: "Tomate, melancia, morango..." },
  { name: "🟠 Coma algo laranja hoje", description: "Cenoura, abóbora, mamão..." },
  { name: "🟣 Coma algo roxo hoje", description: "Uva, beterraba, repolho roxo..." },
  { name: "🔤 Coma uma fruta com a letra A", description: "Abacate, abacaxi, ameixa..." },
  { name: "🔤 Coma um legume com S", description: "Salsa, salsão..." },
  { name: "🔤 Coma algo que comece com M", description: "Melão, manga, mamão..." },
  { name: "🔤 Coma uma fruta com B", description: "Banana, bergamota..." },
  { name: "🌱 Experimente um alimento novo", description: "Algo que você nunca comeu antes!" },
  { name: "🥗 Salada com 5 cores diferentes", description: "Quanto mais colorida, melhor!" },
  { name: "🍎 Coma 3 frutas diferentes hoje", description: "Variedade é tudo!" },
  { name: "🍵 Beba um chá natural", description: "Camomila, hortelã, gengibre..." },
  { name: "🥑 Inclua uma gordura boa", description: "Abacate, castanhas, azeite..." },
  { name: "🌾 Experimente um grão integral", description: "Quinoa, aveia, arroz integral..." },
  { name: "🍋 Comece o dia com água com limão", description: "Hidratação + vitamina C!" },
  { name: "🥕 Coma um vegetal cru hoje", description: "Crocância e nutrientes!" },
  { name: "🐟 Inclua uma proteína magra", description: "Peixe, frango, ovo..." },
  { name: "🌰 Coma um punhado de oleaginosas", description: "Castanhas, amêndoas..." },
  { name: "🌳 Coma algo que cresce em árvore", description: "Frutas, castanhas..." },
  { name: "⚪ Coma algo redondo", description: "Frutas, legumes, ovos..." },
  { name: "🌈 Refeição com arco-íris no prato", description: "Todas as cores possíveis!" },
  { name: "🥥 Coma uma fruta tropical hoje", description: "Coco, manga, abacaxi..." },
  { name: "🥒 Coma um vegetal verde escuro", description: "Couve, espinafre, brócolis..." },
  { name: "🍓 Coma uma fruta vermelha", description: "Morango, framboesa, cereja..." },
  { name: "🥬 Coma uma folha verde", description: "Alface, rúcula, couve..." },
  { name: "🍠 Coma um tubérculo", description: "Batata-doce, inhame, mandioca..." },
  { name: "💧 Beba 2 litros de água hoje", description: "Hidratação em primeiro lugar!" },
  { name: "🥣 Tome uma sopa nutritiva", description: "Quentinha e reconfortante" },
  { name: "🍯 Use mel ao invés de açúcar", description: "Adoçante natural!" },
  { name: "🥛 Experimente um leite vegetal", description: "Amêndoa, aveia, coco..." },
  { name: "🍇 Coma uma fruta pequenininha", description: "Uva, mirtilo, framboesa..." },
  { name: "🌶️ Use uma especiaria diferente", description: "Inova no tempero!" },
  { name: "🥜 Coma uma proteína vegetal", description: "Lentilha, grão-de-bico, feijão..." },
  { name: "🍊 Coma uma fruta cítrica", description: "Laranja, limão, tangerina..." },
  { name: "🌽 Coma algo amarelinho diferente", description: "Mostarda, pimentão amarelo..." },
  { name: "🥝 Coma uma fruta peluda", description: "Kiwi, pêssego..." },
  { name: "🍅 Coma um alimento in natura", description: "Sem cozinhar, puro!" },
  { name: "🥦 Coma um vegetal crucífero", description: "Brócolis, couve-flor..." },
  { name: "🍌 Coma uma fruta de sobremesa", description: "Doce e saudável!" },
  { name: "🥗 Café da manhã colorido", description: "Comece o dia com cor!" },
  { name: "🍲 Cozinhe uma refeição em casa", description: "Cuidado com você mesma 💜" },
  { name: "🌿 Use uma erva fresca", description: "Manjericão, hortelã, salsinha..." },
  { name: "🍐 Coma uma fruta com casca", description: "A casca tem fibras!" },
  { name: "🥚 Inclua um ovo no seu dia", description: "Proteína completa!" },
  { name: "🫐 Coma uma berry", description: "Mirtilo, amora, framboesa..." },
  { name: "🥭 Fruta doce sem açúcar adicionado", description: "Doçura natural!" },
  { name: "🌻 Coma uma semente", description: "Girassol, abóbora, chia, linhaça..." },
  { name: "🍑 Coma uma fruta com caroço", description: "Pêssego, ameixa, manga..." },
  { name: "🥯 Substitua pão branco por integral", description: "Mais fibras pro seu dia!" }
];

// ===== FILMES/SÉRIES =====
const movies = [
  { title: "Bridgerton", type: "Série", year: "2020", genre: "Romance de Época", streaming: "Netflix" },
  { title: "Emily em Paris", type: "Série", year: "2020", genre: "Romance/Comédia", streaming: "Netflix" },
  { title: "Gossip Girl", type: "Série", year: "2007", genre: "Drama Romântico", streaming: "HBO Max" },
  { title: "Gilmore Girls", type: "Série", year: "2000", genre: "Comédia Dramática", streaming: "Netflix" },
  { title: "Anne with an E", type: "Série", year: "2017", genre: "Drama", streaming: "Netflix" },
  { title: "The Crown", type: "Série", year: "2016", genre: "Drama Histórico", streaming: "Netflix" },
  { title: "Wandinha", type: "Série", year: "2022", genre: "Fantasia/Mistério", streaming: "Netflix" },
  { title: "Stranger Things", type: "Série", year: "2016", genre: "Sci-Fi/Fantasia", streaming: "Netflix" },
  { title: "Heartstopper", type: "Série", year: "2022", genre: "Romance", streaming: "Netflix" },
  { title: "Outer Banks", type: "Série", year: "2020", genre: "Aventura", streaming: "Netflix" },
  { title: "Sex Education", type: "Série", year: "2019", genre: "Comédia", streaming: "Netflix" },
  { title: "Euphoria", type: "Série", year: "2019", genre: "Drama", streaming: "HBO Max" },
  { title: "Friends", type: "Série", year: "1994", genre: "Comédia", streaming: "HBO Max" },
  { title: "How I Met Your Mother", type: "Série", year: "2005", genre: "Comédia Romântica", streaming: "Disney+" },
  { title: "The Summer I Turned Pretty", type: "Série", year: "2022", genre: "Romance", streaming: "Prime Video" },
  { title: "Pousando no Amor (CLOY)", type: "Dorama", year: "2019", genre: "Romance", streaming: "Netflix" },
  { title: "Goblin", type: "Dorama", year: "2016", genre: "Romance/Fantasia", streaming: "Netflix" },
  { title: "Pousando em Você", type: "Dorama", year: "2019", genre: "Romance", streaming: "Netflix" },
  { title: "Round 6", type: "Dorama", year: "2021", genre: "Suspense", streaming: "Netflix" },
  { title: "Itaewon Class", type: "Dorama", year: "2020", genre: "Drama", streaming: "Netflix" },
  { title: "Your Name", type: "Anime (Filme)", year: "2016", genre: "Romance/Fantasia", streaming: "Prime Video" },
  { title: "A Viagem de Chihiro", type: "Anime (Filme)", year: "2001", genre: "Fantasia", streaming: "HBO Max" },
  { title: "Meu Amigo Totoro", type: "Anime (Filme)", year: "1988", genre: "Fantasia", streaming: "HBO Max" },
  { title: "Demon Slayer", type: "Anime", year: "2019", genre: "Ação/Fantasia", streaming: "Netflix" },
  { title: "Spy x Family", type: "Anime", year: "2022", genre: "Comédia/Ação", streaming: "Netflix" },
  { title: "Tempestade de Amor (Persuasion)", type: "Filme", year: "2022", genre: "Romance de Época", streaming: "Netflix" },
  { title: "À Espera de um Milagre", type: "Filme", year: "1999", genre: "Drama", streaming: "HBO Max" },
  { title: "La La Land", type: "Filme", year: "2016", genre: "Romance/Musical", streaming: "Netflix" },
  { title: "Diário de uma Paixão", type: "Filme", year: "2004", genre: "Romance", streaming: "HBO Max" },
  { title: "10 Coisas que Eu Odeio em Você", type: "Filme", year: "1999", genre: "Comédia Romântica", streaming: "Disney+" },
  { title: "Legalmente Loira", type: "Filme", year: "2001", genre: "Comédia", streaming: "Prime Video" },
  { title: "Sex and the City: O Filme", type: "Filme", year: "2008", genre: "Comédia Romântica", streaming: "HBO Max" },
  { title: "And Just Like That", type: "Série", year: "2021", genre: "Comédia Romântica", streaming: "HBO Max" },
  { title: "Mulheres Ricas e Solteiras", type: "Filme", year: "2023", genre: "Comédia Romântica", streaming: "Netflix" },
  { title: "Confissões de uma Garota Excluída", type: "Filme", year: "2021", genre: "Comédia", streaming: "Netflix" },
  { title: "Para Todos os Garotos que Já Amei", type: "Filme", year: "2018", genre: "Romance Adolescente", streaming: "Netflix" },
  { title: "Animais Fantásticos", type: "Filme", year: "2016", genre: "Fantasia", streaming: "HBO Max" },
  { title: "Percy Jackson", type: "Série", year: "2023", genre: "Fantasia", streaming: "Disney+" },
  { title: "Once Upon a Time", type: "Série", year: "2011", genre: "Fantasia", streaming: "Disney+" },
  { title: "A Sociedade Literária de Guernsey", type: "Filme", year: "2018", genre: "Romance/Drama", streaming: "Netflix" },
  { title: "Encanto", type: "Filme", year: "2021", genre: "Animação/Musical", streaming: "Disney+" }
];

// ===== DICAS DE LOOK PELO CLIMA =====
const lookRecommendations = {
  chuva: [
    "Trench coat + botinha + guarda-chuva colorido ☔",
    "Jaqueta corta-vento + calça + tênis impermeável 🌧️",
    "Casaco quentinho + cachecol + bota de cano alto ☂️",
    "Vestido midi + meia-calça + galocha estilosa 🌂"
  ],
  muitoQuente: [
    "Vestidinho fresco de alça + sandália rasteirinha + óculos escuros 👗",
    "Short jeans + cropped + tênis branco 🌞",
    "Saia midi + top + sandália + chapéu de palha 🌻",
    "Conjuntinho linho + slide + bolsa de palha ☀️"
  ],
  quente: [
    "Vestido leve + tênis + acessório statement ✨",
    "Calça wide leg + regata + tênis chunky 💫",
    "Saia + camisa branca larguinha + tênis casual 👚",
    "Macaquinho + sandália + brinco grande 🌷"
  ],
  agradavel: [
    "Calça jeans + camiseta básica + cardigan + tênis 🍂",
    "Vestido midi + jaqueta jeans + botinha 🌸",
    "Calça + blusa de manga longa fininha + tênis branco ✨",
    "Saia + meia-calça + suéter + coturno 💜"
  ],
  frio: [
    "Calça + suéter de tricô + casaco + cachecol + bota 🧥",
    "Trench coat + calça + bota de salto + bolsa estruturada ❄️",
    "Calça térmica + blusa + jaqueta puffer + tênis quente 🧣",
    "Vestido + meia-calça grossa + casaco longo + bota de cano alto 🥶"
  ],
  muitoFrio: [
    "Sobreposição: blusa + suéter + casaco + cachecol + gorro 🧤",
    "Calça térmica + moletom + jaqueta puffer + bota forrada ❄️",
    "Look todo preto quentinho + boina + cachecol gigante 🖤",
    "Calça + blusa de gola + casaco longo + luvas + gorro 🥶"
  ]
};
